[versions]
kotlin = "2.3.0"
kotlinx-io = "0.8.2"
kotlinx-serialisation = "1.10.0-RC"
antlr4 = "4.13.2"

[libraries]
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-serialisation = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialisation" }
antlr4 = { module = "org.antlr:antlr4", version.ref = "antlr4" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialisation = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }